Feature/pokemon details page
justcier/pokedex pull request #3
Opened 2023-04-12 14:18 UTC by justcier

What was done:

- Added pokemon_details_page feature
- Added custom loader
- Added tests data in json files

**Screen:**
<img width="239" alt="Screenshot 2023-04-11 at 13 31 14" src="https://user-images.githubusercontent.com/71925819/231485773-4bb939bb-1ad7-4078-a044-332e8c1e880e.png">

**Video:**
https://user-images.githubusercontent.com/71925819/231485979-9b268392-c1a9-410a-ae7c-1c2aef80f42f.mov

2023-04-12 17:05 UTC, bkkoluch commented
> What was done:
> 
> * Added pokemon_details_page feature
> * Added custom loader
> * Added tests data in json files
> 
> **Screen:** <img alt="Screenshot 2023-04-11 at 13 31 14" width="239" src="https://user-images.githubusercontent.com/71925819/231485773-4bb939bb-1ad7-4078-a044-332e8c1e880e.png">
> 
> **Video:** https://user-images.githubusercontent.com/71925819/231485979-9b268392-c1a9-410a-ae7c-1c2aef80f42f.mov

1) `pokemon_defailts` feature instead of `pokemon_details_page` feature

2) video is not uploaded correctly :(

2023-04-12 17:19 UTC, bkkoluch requested changes

2023-04-12 17:19 UTC, bkkoluch commented on README.md
> +| Navigation  | auto_route |
Nice 👍

2023-04-12 17:19 UTC, bkkoluch commented on lib/common/widgets/pokeball_loader.dart
> +    // controller.forward();
Missing comma and unnecessary commented line

2023-04-12 17:19 UTC, bkkoluch commented on lib/common/widgets/pokemon_hero.dart
> +  const PokemonHero({
Missing empty line

2023-04-12 17:19 UTC, bkkoluch commented on lib/features/pokemon_details/presentation/pages/pokemon_details_page.dart
> +                )),
Missing comma at the end , and you're using `Container` when `Padding` would be enough, also - you could make it const ;), try to use the most specific widgets and try to avoid the most generic ones (for example: if you're only using color in the `Container`, use `ColoredBox` instead)

2023-04-12 17:19 UTC, bkkoluch commented on lib/features/pokemon_details/presentation/pages/pokemon_details_page.dart
> +            ),
Delete comma

2023-04-12 17:19 UTC, bkkoluch commented on lib/features/pokemon_details/presentation/pages/pokemon_details_page.dart
> +            ),
As above

2023-04-12 17:19 UTC, bkkoluch commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +            child: Column(
Unnecessary `Container`, you can use `Padding`

2023-04-12 17:19 UTC, bkkoluch commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +                      child: _BaseStatsRow(
As above

2023-04-12 17:19 UTC, bkkoluch commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +                          statName: statName, statValue: statValue),
Missing commas

2023-04-12 17:19 UTC, bkkoluch commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +                  child: _BaseStatsRow(
Unnecessary `Container`, use `Padding` when using only `padding`

2023-04-12 17:19 UTC, bkkoluch commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +                    statName: 'experience',
Why not extract it to `strings.dart`?

2023-04-12 17:19 UTC, bkkoluch commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +                color: Colors.white,
Try not to use material colors, but your own when you have `ColorTokens`

2023-04-12 17:19 UTC, bkkoluch commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +          pokemonNameStatsToShortcuts[widget.statName]!,
You're using `!` operator here, the app will crash if it returns null, maybe some null check?

2023-04-12 17:19 UTC, bkkoluch commented on lib/features/pokemon_list/presentation/widgets/pokemon_list_widget.dart
> +          child: PokemonTileContent(pokemonDetails: pokemonDetailsList[index]),
You can extract `pokemonDetailsList[index]` to a variable

2023-04-12 17:19 UTC, bkkoluch commented on lib/main.dart
> +  MyApp({super.key});
Why isn't it const anymore?

2023-04-12 17:19 UTC, bkkoluch commented on lib/style/text_style_tokens.dart
> +// GoogleFonts.pressStart2PTextTheme
Unnecessary comment

2023-04-12 20:19 UTC, justcier commented on lib/common/widgets/pokemon_hero.dart
> +  const PokemonHero({
Done

2023-04-12 20:25 UTC, justcier commented on lib/features/pokemon_details/presentation/pages/pokemon_details_page.dart
> +                )),
Done

2023-04-12 20:25 UTC, justcier commented on lib/features/pokemon_details/presentation/pages/pokemon_details_page.dart
> +            ),
Done

2023-04-12 20:27 UTC, justcier commented on lib/style/text_style_tokens.dart
> +// GoogleFonts.pressStart2PTextTheme
Done

2023-04-12 20:29 UTC, justcier commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +            child: Column(
Done

2023-04-12 20:30 UTC, justcier commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +                      child: _BaseStatsRow(
Done

2023-04-12 20:32 UTC, justcier commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +                          statName: statName, statValue: statValue),
Done

2023-04-12 20:32 UTC, justcier commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +                  child: _BaseStatsRow(
Done

2023-04-12 20:34 UTC, justcier commented on lib/common/widgets/pokeball_loader.dart
> +    // controller.forward();
Done

2023-04-13 09:35 UTC, justcier commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +                    statName: 'experience',
Done

2023-04-13 09:38 UTC, justcier commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +                color: Colors.white,
Done

2023-04-13 10:00 UTC, justcier commented on lib/features/pokemon_details/presentation/widgets/pokemon_details_stats_container.dart
> +          pokemonNameStatsToShortcuts[widget.statName]!,
Done

2023-04-13 10:15 UTC, justcier commented on lib/features/pokemon_list/presentation/widgets/pokemon_list_widget.dart
> +          child: PokemonTileContent(pokemonDetails: pokemonDetailsList[index]),
Done

2023-04-13 10:25 UTC, merged