Feature/search pokemon
justcier/pokedex pull request #6
Opened 2023-06-13 13:47 UTC by justcier

What was done:

- Added SliverAppBar to PokemonListPage - search field
- Added SearchCubit
- Added error handling when user put wrong name in search
- Added SearchTileContent
- Added tests

**Screen:**
||||
| ------- | ------ | ------ |
|<img width="294" alt="Screenshot 2023-06-13 at 15 28 31" src="https://github.com/justcier/pokedex/assets/71925819/8bbdc306-6ef8-4e81-b4bb-907e8c34d1c1">|<img width="291" alt="Screenshot 2023-06-13 at 15 28 57" src="https://github.com/justcier/pokedex/assets/71925819/e3cff5bd-feb1-475c-984e-84f80e3b5af8">|<img width="288" alt="Screenshot 2023-06-13 at 15 29 13" src="https://github.com/justcier/pokedex/assets/71925819/34b310c7-6bb7-4a16-bc28-c7e6e95b8fac">|

2023-06-13 14:11 UTC, bkkoluch requested changes

2023-06-13 14:11 UTC, bkkoluch commented on lib/common/widgets/pokemon_button.dart
> +  final Function() onTap;
Change `Function()` to `VoidCallback` as it's an already existing typedef :)

2023-06-13 14:11 UTC, bkkoluch commented on lib/common/widgets/pokemon_button.dart
> +        margin: const EdgeInsets.all(Dimensions.sizeXL),
Why both?

2023-06-13 14:11 UTC, bkkoluch commented on lib/common/widgets/pokemon_summary.dart
> +  const PokemonSummary({
Space

2023-06-13 14:11 UTC, bkkoluch commented on lib/core/strings/strings.dart
> +    return 'Pokemon with name:\n\n \'$textFieldValue\' \n\ndoes not exist!'
Why the space between `\n` and `\'$textFieldValue\'`?

2023-06-13 14:11 UTC, bkkoluch commented on lib/core/strings/strings.dart
> +    return 'Pokemon with name:\n\n \'$textFieldValue\' \n\ndoes not exist!'
And why use double `\n`s?

2023-06-13 14:11 UTC, bkkoluch commented on lib/features/search/presentation/widgets/error_view_widget.dart
> +          },
You could pass only one parameter - `final VoidCallback onTap` and pass the ```() {
            controller.clear();
            pokemonListCubit.searchCubit.clearSearch();
          }``` there

2023-06-13 14:11 UTC, bkkoluch commented on lib/features/search/presentation/widgets/search_tile_content.dart
> +      padding: const EdgeInsets.all(Dimensions.sizeL),
If you're using only `padding` parameter, use `Padding` instead of `Container`

2023-06-13 14:11 UTC, bkkoluch commented on lib/features/search/presentation/widgets/search_tile_content.dart
> +                    .copyWith(fontSize: Dimensions.sizeXL),
Seems like a new font style to be created :D, instead of doing `.copyWith`

2023-06-13 14:11 UTC, bkkoluch commented on lib/features/search/presentation/widgets/search_tile_content.dart
> +                },
Same case, you're passing `clearSearchField` and `pokemonCubit`, why not pass `onTap` and use both of them there?

2023-06-13 14:11 UTC, bkkoluch commented on lib/features/search/presentation/widgets/search_widget.dart
> +  }
Why `late` and not initialise it immediatelly?

2023-06-13 14:11 UTC, bkkoluch commented on lib/features/search/presentation/widgets/search_widget.dart
> +                .copyWith(color: ColorTokens.secondaryColor, fontSize: 8),
Another one to extract

2023-06-14 07:36 UTC, justcier commented on lib/common/widgets/pokemon_button.dart
> +  final Function() onTap;
Done

2023-06-14 07:43 UTC, justcier commented on lib/common/widgets/pokemon_button.dart
> +        margin: const EdgeInsets.all(Dimensions.sizeXL),
Padding added to SearchTileContent. Thanks!

2023-06-14 07:47 UTC, justcier commented on lib/common/widgets/pokemon_summary.dart
> +  const PokemonSummary({
Done

2023-06-14 07:49 UTC, justcier commented on lib/core/strings/strings.dart
> +    return 'Pokemon with name:\n\n \'$textFieldValue\' \n\ndoes not exist!'
Done

2023-06-14 07:58 UTC, justcier commented on lib/features/search/presentation/widgets/error_view_widget.dart
> +          },
Done.

2023-06-14 08:00 UTC, justcier commented on lib/features/search/presentation/widgets/search_tile_content.dart
> +      padding: const EdgeInsets.all(Dimensions.sizeL),
Done

2023-06-14 08:11 UTC, justcier commented on lib/features/search/presentation/widgets/search_tile_content.dart
> +                    .copyWith(fontSize: Dimensions.sizeXL),
Done

2023-06-14 08:24 UTC, justcier commented on lib/features/search/presentation/widgets/search_widget.dart
> +                .copyWith(color: ColorTokens.secondaryColor, fontSize: 8),
Done

2023-06-14 08:31 UTC, justcier commented on lib/features/search/presentation/widgets/search_widget.dart
> +  }
Done

2023-06-14 08:51 UTC, justcier commented on lib/features/search/presentation/widgets/search_tile_content.dart
> +                },
Done

2023-06-14 08:52 UTC, bkkoluch commented on lib/features/pokemon_list/presentation/pages/pokemon_list_page.dart
> +                        },
The function is doubled, line 107, you can extract it and use a tear-off here

2023-06-14 09:00 UTC, justcier commented on lib/features/pokemon_list/presentation/pages/pokemon_list_page.dart
> +                        },
Done

2023-06-14 09:02 UTC, bkkoluch approved these changes

2023-06-14 09:02 UTC, merged